### ISSUE TITLE
lzdoom: OpenGL renderer & output resolution gets resetted

### ISSUE THREAD

**Issue by Crushless** [351ELEC/351ELEC-beta#13]
Hello,

lzdoom is set to software renderer by default. I tired to set it to OpenGL, but lzdoom says, that I have to restart it for the change to take effect. After restarting lzdoom, the setting gets automatically reset to software renderer. I tried to change the setting in the lzdoom.ini, but this also has no effect. Changing the output resolution is applied instant and works just fine while lzdoom is running, but gets also reset after a restart.

1. lzdoom should per default use OpenGL as the renderer, because most of the devices have a fairly capable GPU, and most of the other emulators already render on OpenGL per default
2. 351ELEC should always respect the users changes on emulator settings and never try to overrule them
3. Probably add a menu function which allows the user to reset an emulators settings to default fail-safe values, if something goes horribly wrong

**Comment by dhwz** [comment]
This hardware doesn't support OpenGL.

**Comment by Crushless** [comment]
Most devices do. For example, the device I tried (RG351MP), has an Mail G31-MP2

Even **if** the hardware does not support OpenGL, 351ELEC should **never** override explicit user settings. Sometimes the user knows better (I noticed no problems running on a higher resolution, for example).

**Please reopen this issue.**

![Screenshot 2021-11-13 at 11-40-21 RG351MP Review - The latest retro gaming handheld by Anbernic](https://user-images.githubusercontent.com/28498576/141615496-83f270a2-7159-418b-925d-32daadd4b88b.png)
![Screenshot 2021-11-13 at 11-39-43 Mali-G31 GPU – Arm Developer](https://user-images.githubusercontent.com/28498576/141615500-12d50397-8486-4bdd-8a1b-9eb44c5d13e7.png)

**Comment by dhwz** [comment]
No they don't OpenGL ES is not OpenGL

**Comment by Crushless** [comment]
I'm not a native English speaker, so please forgive me if my request sounded a bit harsh and not as polite as it should. I would never try to told you, what you have to do. I only made an suggestion what you could/should do from an users perspective. I always find it frustrating, if a software silently ignores a setting without any user feedback, and I have to figure out why.

Thank you for this information. I know now, that this is not an issue with 351ELEC, and that 351ELEC only wants to protect its users from bad settings.

I will create an issue in lzdoom to support OpenGL ES in the future.

**Comment by dhwz** [comment]
You don't need to open a request for lzdoom, just wait for next release in working on something.
