### ISSUE TITLE
inverted left stick 

### ISSUE THREAD

**Issue by AlexParkerNY** [351ELEC/351ELEC-beta#2]
Inverted the stick in ports and some emulators for example Retrorun / Flycast and mupen64plussa / m64 rice, opentyrian.

**Comment by RyuuSlayer** [comment]
Can repliace for Retrorun / Flycast

**Comment by M1ch3l77** [comment]
Retrun/flycast is fixed on last beta and opentyrian, you have to configure stick in options.

**Comment by dhwz** [comment]
@M1ch3l77 no thats not the bug that was in retrorun.
The analog is inverted by the hardware itself, we won't really fix that. It has always been like that.
