### ISSUE TITLE
Unable to run some OpenBOR games

### ISSUE THREAD

**Issue by 1900forever** [351ELEC/351ELEC-beta#4]
Describe the bug
Under beta-20210929_2223
The system went black screen while running certain OpenBOR game:
https://1drv.ms/u/s!AnTXKPMHlONnhNRY2xHFdLO7X39WQw?e=vQiUJq

made by: https://fgames9000.blogspot.com/

To Reproduce
Run SOR2X_V2.3.1.pak, then the system went black screen after loaded the game.
No hotkeys work, I have to long press the power key to force shut down.

**Comment by dhwz** [comment]
Killing a game process should work with L2 + Select + Start
Sorry we can't fix emulator related issues, if it's not working then please report the issue at the upstream git https://github.com/DCurrent/openbor

**Comment by 1900forever** [comment]
Sorry to bother again. I have tried the same pak file on ArkOS on my RGB10, it works fine.
I don't really know how 351elec uses openbor port, but maybe this info helps. Thanks!

**Comment by 1900forever** [comment]
> Killing a game process should work with L2 + Select + Start Sorry we can't fix emulator related issues, if it's not working then please report the issue at the upstream git https://github.com/DCurrent/openbor

Sorry to bother again. I have tried the same pak file on ArkOS on my RGB10, it works fine.
I don't really know how 351elec uses openbor port, but maybe this info helps. Thanks!

**Comment by dhwz** [comment]
That doesn't help ArkOS uses a old version of OpenBOR, we use one of the newest versions from their git, so if it not works you have to report it there.
