### ISSUE TITLE
351MP: Wifi/OTA port not working after sleep

### ISSUE THREAD

**Issue by pkegg** [351ELEC/351ELEC-beta#5]
# Summary
When putting the 351MP to sleep, there is a kernel crash.  The result of this is:
- The OTA port stops functioning
- The 'resume' actions don't run.  This mainly means the sound gets set back to default 50%

OTA/wifi works again only after reboot.

**Comment by dhwz** [comment]
fixed https://github.com/351ELEC/351ELEC/commit/9ca14db6d083d32a7b6dbb195072712b6573103d
